version: '3.7'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
#      - 443:443
    volumes:
      - ./docker/nginx/dev:/etc/nginx/conf.d
#      - ./docker/nginx/certbot/conf:/etc/letsencrypt
#      - ./docker/nginx/certbot/www:/var/www/certbot
    networks:
      - my-network
#
#  certbot:
#    image: certbot/certbot
#    restart: unless-stopped
#    volumes:
#      - ./docker/nginx/certbot/conf:/etc/letsencrypt
#      - ./docker/nginx/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  frontend-ui:
    build: .
    ports:
      - "3000:3000"
    container_name: frontend-ui
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    networks:
      - my-network

networks:
  my-network:
